title: learningis1st
author:
  name: Yijia Chen
  email: chenyijia001@gmail.com

description: >-
  A Boring Blog

baseurl: ""
url: "https://learningis1.st"

theme: minima

plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap

header_pages:
  - about.md
  - openpgp.md

minima:
  skin: auto
  #date_format: "%b-%d-%Y"
  social_links:
    - { platform: github, user_url: "https://github.com/learningis1st" }
    - { platform: keybase, user_url: "https://keybase.io/learningis1st" }
    - { platform: telegram, user_url: "https://t.me/learningis1st" }
    - { platform: twitter, user_url: "https://twitter.com/learningis1st" }

include: [".well-known"]
